### ISSUE TITLE
TS2339: Property 'initialize' does not exist on type '(hjid: number, hjsv: number) => void'.

### ISSUE THREAD

**Issue by muneebahmad222** [abdalla/react-hotjar#14]
React Build failed with this error. I had this code in place for like a couple of months but since yesterday it is failing

**Comment by tenshouuu** [comment]
+ 1, I have the same issue

**Comment by Elyjohn** [comment]
My bad, i made a [Pull request #15](https://github.com/abdalla/react-hotjar/pull/15) to fix it.

**Comment by Elyjohn** [comment]
I made a PR (#16) to fix it.

**Comment by abdalla** [comment]
Just pushed new version.

Thanks @Elyjohn for the PR
