### ISSUE TITLE
Where I have to initialize?

### ISSUE THREAD

**Issue by jcruzsocial** [abdalla/react-hotjar#20]
I have to initialize before the App or inside the App component?

**Comment by reenan** [comment]
You can initialize it right after rendering your App.
I don't see anything wrong with initializing it in or before the App as well, it's up to you.

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { hotjar } from 'react-hotjar';

ReactDOM.render(
  <App />,
  MOUNT_NODE
);

hotjar.initialize(HOTJAR_ID, HOTJAR_SV);
```

**Comment by abdalla** [comment]
Closing this issue.

Thanks @reenan
