### ISSUE TITLE
How can I pass user attributes?

### ISSUE THREAD

**Issue by yrik** [abdalla/react-hotjar#23]
I would like to provide user id and other information to hotjar
https://help.hotjar.com/hc/en-us/articles/360038394053

**Comment by abdalla** [comment]
Today it is not possible.

I'm considering to implement it as soon as I get a chance, or you can do it and open a PR.

Thanks

**Comment by Checknovac** [comment]
@yrik you could try https://github.com/olavoparno/react-use-hotjar
