### ISSUE TITLE
How can I add preconnect or dns prefetch attribute?

### ISSUE THREAD

**Issue by muserrefakillibaykus** [abdalla/react-hotjar#24]
<img width="831" alt="Ekran Resmi 2020-05-21 23 07 55" src="https://user-images.githubusercontent.com/64922778/82601370-211c1e00-9bb8-11ea-87d6-84cbd4671392.png">

**Comment by abdalla** [comment]
Today it is not possible.

You can implement it and open a PR.

**Comment by muserrefakillibaykus** [comment]
I don't know how can i do this. Can you do it please? @abdalla

**Comment by abdalla** [comment]
Sure, but I'm involved in other projects, I have no time to focus on it right now. Sorry!
