### ISSUE TITLE
Next.JS Implementation. 

### ISSUE THREAD

**Issue by jonrrivera** [abdalla/react-hotjar#26]
Thanks for the great module. It would be nice if there was a next.js implementation. For the moment I was able to verify using:

```
if (typeof window !== "undefined") {
      hotjar.initialize(hjid, hjsv);
}
```

**Comment by MatheusPoliCamilo** [comment]
I used with [React useEffect](https://reactjs.org/docs/hooks-effect.html) and worked fine

```
import { hotjar } from 'react-hotjar'

export default function Index() {
  useEffect(() => {
    hotjar.initialize(hjid, hjsv)
  })

 return ({/* Your code here */})
}
```

**Comment by NKANGIJAFARI** [comment]
Hey @jonrrivera  and @MatheusPoliCamilo
In which component did you add this code so it can run on all pages.
Can I use it as a layout to be on top or as a wrapper component that returns the rest as children

**Comment by lenivene** [comment]
> Hey @jonrrivera and @MatheusPoliCamilo In which component did you add this code so it can run on all pages. Can I use it as a layout to be on top or as a wrapper component that returns the rest as children

To use with `next.js` add in file `_app.jsx` or `_app.tsx`

**Comment by lenivene** [comment]
> Is there any way of initializing hotjar after a clicking event, and not when mounting a component? In the scenario where the user consent for cookies, to then initialize hotjar.
> 
> EDIT: nvm, I actually can use it for instance onClick. I had just forgotten to clear my cookies in order to see the hotjar request after clicking... see_no_evil

```ts
const [handleAcceptHotjar, setHandleAcceptHotjar] = useState(false);

useEffect(() => {
  if(handleAcceptHotjar){
  // execute function
  }
}, [handleAcceptHotjar]);
```
In button
```tsx
<button type="button" onClick={() => setHandleAcceptHotjar(true)}>
  Accept
</button>
```

**Comment by sagarromer** [comment]
any good example or code snippet on how to add hotjar when button is clicked for a react application?
