### ISSUE TITLE
Identify is not sending email

### ISSUE THREAD

**Issue by carlosost** [abdalla/react-hotjar#34]
Hi,

I would like to know if there is any known issue while using the function `hotjar.identify('USER_ID', { userProperty: user.email });`, because we are using it and getting `USER_ID` at Hotjar dashboard, instead of the `user.email`. 

Our account is a Business type account, which is the right one to have this functionality working.

![Screen Shot 2022-01-24 at 18 10 16](https://user-images.githubusercontent.com/12072335/150865443-b6158938-e0c5-4c80-b441-634194824158.png)

**Comment by westrem** [comment]
You need to replace the `USER_ID` with the actual id of the user. The following object is then used to attach custom attributes to that user. 

So in your case imagine an user with id `123` and email `usr123@example.com`.

What you want to do is this call:

```
hotjar.identify('123', { email: 'usr123@example.com' });
```

**Comment by carlosost** [comment]
Ok... I see...

According to Hotjar [documentation](https://help.hotjar.com/hc/en-us/articles/360033640653#handling-email-addresses), the JS function to use would be:
```
hj('identify', userId, { email: 'test@test.com' });
```
And now I understand this package makes a wrapper of this function where `identify` was black boxed and `userid` was mapped to `USER_ID`, right?

I will test and come back with the results.

Thank you.
