### ISSUE TITLE
Removing hotjar tracking

### ISSUE THREAD

**Issue by leahtopchik** [abdalla/react-hotjar#39]
Is there a way or can there be a way to remove hotjar tracking with this package? 

Use case: If a user has previously accepted cookies but then changes those setting hotjar will need to be disabled. I can clear the cookie but it won't remove the tracking code.

**Comment by bde-maze** [comment]
Up 👍 
I would like to do the same.

The solution i use for now is to unset all cookies starting by __hj_

**Comment by abdalla** [comment]
No.

PR is welcome to do that.
