### ISSUE TITLE
Compatibility with Next.js

### ISSUE THREAD

**Issue by kytwb** [abdalla/react-hotjar#4]
Is this module compatible with Next.js?  
I tried to use it within a Next.js project but I couldn't verify my local install via HotJar website. My local website would open in a new tab, but I wouldn't get the success message / popup. I tried to call the `initialize` method in my component `componentDidMount` method so it's only executed when the code render/mount(?) client-side, but it didn't work.

**Comment by abdalla** [comment]
Please, provide the versions of the components you are using and the code.

I never used it with next, but you shouldn't have any trouble.

**Comment by kytwb** [comment]
This was just me not knowing how-to use Next.js, my bad :) Thanks for the module ❤️

**Comment by okbrown** [comment]
@kytwb would you mind sharing how you got it working in nextjs?

**Comment by mledwards** [comment]
Remember in a functional component to run in a useEffect, so it only runs on the client side.

`import { useUserData } from "../lib/users";
import Navbar from "./Navbar";
import Footer from "./Footer";
import SEO from "./SEO";
import { hotjar } from "react-hotjar";

export default function Layout({ children }) {

  React.useEffect(() => {
    // Initialise Hotjar only client side
    hotjar.initialize(2446921, 6);
  }, []); // Only run once

  return (
    ...
  );
}
`
