### ISSUE TITLE
Please include a changelog

### ISSUE THREAD

**Issue by mattfelten** [abdalla/react-hotjar#48]
Doing my semi-annual dependency upgrades and I'm able to upgrade `react-hotjar` from 4 to 5. But it's quite challenging to figure out what breaking change warranted a major release without a changelog or release notes of any kind.

**Comment by abdalla** [comment]
Ok!
Next major release I'll add it.

**Comment by dartess** [comment]
@abdalla it seems the next major is out and i don't understand what has changed and can i update

**Comment by abdalla** [comment]
This major was related to code improvement, not features themselves...

**Comment by mattfelten** [comment]
@abdalla it's very difficult for anyone using your package to know that without a changelog or release notes.
