### ISSUE TITLE
Babel failing to transpile after bumping upto 5.5.0

### ISSUE THREAD

**Issue by abhikarsh-gupta** [abdalla/react-hotjar#54]
```
./node_modules/react-hotjar/index.js 15:60
Module parse failed: Unexpected token (15:60)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     },
|     initialized: function initialized() {
>       return typeof window !== 'undefined' && typeof window?.hj === 'function';
|     },
|     identify: function identify(userId, properties) {
```

Getting the above error when trying to start the application. 

Configs:- CRA with no webpack config. 

    "react-scripts": "4.0.3",
    "babel-plugin-preval": "^5.1.0",
    
    
Kindly look into the issue.
Please let me know if more information is needed. Thanks!

**Comment by jamesl1001** [comment]
Me too. It's caused by the optional chaining (`?.`) here: https://github.com/abdalla/react-hotjar/blob/master/index.js#L18

Downgrading to `react-hotjar@5.4.1` has temporarily solved it for me.

**Comment by Mihai-github** [comment]
Hey, came across the same problem ... the only solution is downgrading to `react-hotjar@5.4.1`?

**Comment by abdalla** [comment]
Could you try the v 6 ?
