### ISSUE TITLE
Hotjar not working after login

### ISSUE THREAD

**Issue by Mihai-github** [abdalla/react-hotjar#55]
Hello,

    I'm having an issue with the user's auth session on our website. The Hotjar seems to work just fine outside a logged session page but after the user goes to login/register the recording stops and we currently don't have any idea how to find out why.

Dependencies 
`
"react-hotjar": "^5.0.0",
`

**Comment by abdalla** [comment]
I have no time to get into this right now, please downgrade to version 5.4.1....

PR is welcome!
