### ISSUE TITLE
Next.js: "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by felipecornejo1** [abdalla/react-hotjar#61]
Hi there, I'm trying to integrate this library with a next.js application, so I added the following piece of code to my `_app.tsx`:
```typescript
import { hotjar } from 'react-hotjar'

function MyApp({ Component, pageProps }: AppProps) {
 
  useEffect(() => {
    if (typeof window !== 'undefined') hotjar.initialize(3578249, 6)
  }, [])

  return (
    <>
      ...My components
    </>
  )
```

when I try to build, I get the following error:

```
import hotjarLib from './src/react-hotjar';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 5716 (C:\Users\phili\Documents\repos\takenos-repos\takenos-monorepo\packages\web\.next\server\pages\_document.js:218:18)
    at __webpack_require__ (C:\Users\phili\Documents\repos\takenos-repos\takenos-monorepo\packages\web\.next\server\webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
error Command failed with exit code 1.
```
I've taken a look at this file inside `node_modules` and it's not doing any imports, so I honestly don't know where to look

**Comment by b1n1yam** [comment]
I encountered the same issue as well. To address the problem, I had to revert to a previous version. Currently, I'm using `V 5.5.0.`

**Comment by bde-maze** [comment]
Same here, why this issues has been closed?
Is there anyway to solve this issue?

**Comment by ivandata** [comment]
Confirm, not working with nextjs

**Comment by ivandata** [comment]
> Same here, why this issues has been closed? Is there anyway to solve this issue?
Add the package into your Next.js config.
`
module.exports = {
    transpilePackages: ['react-hotjar'],
    /* Your Next.js config */
};
`

**Comment by eliawk** [comment]
@ivandata even with `transpilePackages: ['react-hotjar']` I'm still getting the same error:

```
import hotjarLib from './src/react-hotjar';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by goodpilotfish** [comment]
@eliawk I hope it worked out. I had to restart the Next.js server to make it work. If you still have problems, perhaps you can post your next.config.js?

**Comment by dev-m-work** [comment]
> @ivandata even with `transpilePackages: ['react-hotjar']` I'm still getting the same error:
> 
> ```
> import hotjarLib from './src/react-hotjar';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
> ```

Hey @eliawk, from where do you import the package ?

For us importing from `Layout.tsx` works
```tsx
import { hotjar } from "react-hotjar"
```

**Comment by eliawk** [comment]
hey @dev-m-work thanks for your reply. finally I've loaded hotjar without the script - I will take a look with your suggestion as soon as I can.
