### ISSUE TITLE
hotjar.initialize Expected 1 arguments, but got 2

### ISSUE THREAD

**Issue by sergei-lobanov** [abdalla/react-hotjar#71]
Updating from 6.2.0 to 6.3.1 I see the next issue

TS2554: Expected 1 arguments, but got 2.
    47 |     });
    48 |
  > 49 |     hotjar.initialize(Number(process.env.REACT_APP_HOTJAR_ID), 6);
       |                                                                ^
    50 |
    51 |     // Initialize Sentry instance before React
    52 |     initializeSentry();
    
    In the absence of a changelog, it's difficult to determine definitively whether this is a breaking change and something should be changed in the code above or its a bug?

**Comment by arifszn** [comment]
Sad to see breaking changes getting merged into minor releases.

```ts
hotjar.initialize({ id: Number(process.env.REACT_APP_HOTJAR_ID), sv: 6 });
```

**Comment by sergei-lobanov** [comment]
Thanks, works with the changes above, should be good to add this info somewhere with a notice that a breaking change and how to perform a migration

**Comment by abdalla** [comment]
PR's are welcome, be my guest to fix.
