### ISSUE TITLE
initialize is not defined when using with jest

### ISSUE THREAD

**Issue by Anne-Anq** [abdalla/react-hotjar#9]
Hi, 
I am using hotjar for my app. I have no problem using it but when I test a file with jest that has "import { hotjar } from 'react-hotjar'"
I get an error from jest that 'initialize is undefined' and I can't test my component.
If I go into node_modules and replace 
`module.exports = {
  hotjar: {
    initialize: (initialize = (id, sv) => {
      hotjar(id, sv)
    })
  }
}`
by 
`module.exports = {
  hotjar: {
    initialize: (hotjar.initialize = (id, sv) => {
      hotjar(id, sv)
    })
  }
}`
it works but of course that is not sustainable. 
AnyIdea how I can fix it?
I am using `"react-hotjar": "^2.0.0"`

**Comment by abdalla** [comment]
Hi @Anne-Anq try to update your version to 2.0.2 and let me know if it works.

Thanks

**Comment by abdalla** [comment]
Since this issue has no longer interaction, I'm closing.
